// <auto-generated />
namespace PassionProject_TiffinSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class schedulemeal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(schedulemeal));
        
        string IMigrationMetadata.Id
        {
            get { return "202302172343496_schedule-meal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
